<?
/**
 * @author <%= author %>
 * @date <%= date %>
 * project proudly generated by generater-mis, 
 * for more info visit :https://github.com/tbfe/generator-mis
 */
$this->display("<%= projectName %>/index.php");
?>
